# Configuração Jekyll para GitHub Pages
title: "Águias Vitrine - Tudo em Oferta"
description: "As melhores ofertas em moda, beleza, eletrônicos, casa e ebooks exclusivos em um só lugar!"
url: "https://aguias-vitrine.github.io"
baseurl: ""

# Configurações do site
author: "Águias Vitrine"
email: "tudoemperta123@gmail.com"
instagram: "@tudoemofertas123"

# SEO
lang: pt-BR
timezone: America/Sao_Paulo

# Jekyll
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Configurações de build
safe: true
incremental: false
profile: false

# Exclusões
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github

# Configurações de assets
sass:
  style: compressed
  sass_dir: _sass

# Configurações de performance
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Configurações de SEO
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/og-image.jpg"

# Social
social:
  name: "Águias Vitrine"
  links:
    - "https://instagram.com/tudoemofertas123"
    - "mailto:tudoemperta123@gmail.com"

# Google Analytics (substitua pelo seu ID)
google_analytics: "GA_MEASUREMENT_ID"

# Configurações de tema
theme: minima

# Configurações customizadas
collections_dir: collections

# Configurações de navegação
navigation:
  - name: "Início"
    url: "#home"
  - name: "Categorias"
    url: "#categorias"
  - name: "Ofertas"
    url: "#ofertas"
  - name: "Ebooks"
    url: "#ebooks"
  - name: "Contato"
    url: "#contato"

# Configurações de produtos
categories:
  - name: "Moda Feminina"
    slug: "moda"
    icon: "fas fa-tshirt"
    count: "120+"
  - name: "Calçados"
    slug: "calcados"
    icon: "fas fa-shoe-prints"
    count: "80+"
  - name: "Beleza"
    slug: "beleza"
    icon: "fas fa-palette"
    count: "95+"
  - name: "Eletrônicos"
    slug: "eletronicos"
    icon: "fas fa-mobile-alt"
    count: "60+"
  - name: "Casa & Decoração"
    slug: "casa"
    icon: "fas fa-home"
    count: "75+"
  - name: "Ebooks & Cursos"
    slug: "ebooks"
    icon: "fas fa-book"
    count: "50+"
